### ISSUE TITLE
Cannot compile with clang on OS X 10.11.6

### ISSUE THREAD

**Issue by gvoysey** [nclack/whisk#33]
see [buildlog.txt](https://github.com/nclack/whisk/files/614507/buildlog.txt)  for full transcript. 

The compiler warnings generated suggest that perhaps this project only builds with gcc -- is that correct?

**Comment by tvajtay** [comment]
I've tried to build from the source from multiple times and I've never been successful. Personally I just used the pre-built binaries from the [lab homepage.] (https://openwiki.janelia.org/wiki/display/MyersLab/Whisker+Tracking+Downloads)

**Comment by nclack** [comment]
My guess is that the problem is with how I used the inline keyword.  It looks like the inlined functions are not exposed to the linker and that is what generates the linker error at the end of the build log.

It's pretty likely that when I wrote the code,  the compilers I used simply ignored the inline statement so everything worked.  Now that c99 compilers are more prevalent inlining actually has an effect.  In this case it's an unintended one.   It may be that simply removing all uses of the inline keyword may fix the problem.

If you can use the pre-built binaries that's awesome, but there are a number of labs that want to build the code themselves so they can customize things for their own work.

As you can probably tell from the warnings, there are many things I'd fix in the code if I had the time.  I'm very open to accepting pull-requests that fix these things.

**Comment by gvoysey** [comment]
@nclack thanks for the explanation.  What was your build environment when developing this codebase?  

I'm not sure I'll have time or skill to update and send a pull request, but I will do so if occasion warrants.

**Comment by nclack** [comment]
I targeted Max OSX 10.5,  GNU/Linux 2.6.15 (RedHat?), and Windows (Visual Studio 2010?).  That may give you a sense as to what the environments were.  Most of the development was done using OS X.

Incidentally, the hardest part about maintaining the code is testing on different environments.  Any help with getting Docker containers that build the code, or continuous integration tools like Travis/AppVeyor etc is also a huge help.

**Comment by gvoysey** [comment]
@nclack  thanks.  I can _probably_ get a dockerfile for the linux build in shape, actually; i have some of that experience.   I've done travis integration for python (see [here](https://github.com/gvoysey/corti/blob/master/.travis.yml) for the stupid hoops  you have to jump through to get a scipy stack up ), so I can give that a shot too.  

Do you happen to remember if OSX 10.5 was using gcc or clang?  Do you remember if you were using things like homebrew's GNU coreutils vs. the BSD-y ones that come by default?

**Comment by nclack** [comment]
Using brew.  Don't remember gcc v clang.  I seem to remember is was about the time that became very confusing on OSX.

**Comment by gvoysey** [comment]
unfortunately that's all i remember too.  I'll give it a shot.

**Comment by tvajtay** [comment]
@gvoysey @nclack gcc 4.X seems to be able to compile successfully in a Debian environment. Apart from gcc and g++ being the older version, everything else was the current version. (bison, awk, cmake, debian, etc.) I was also able to compile Load/SaveMeasurements in mex, but Load/Savewhiskers is not compiling very easily.

**Comment by nclack** [comment]
@tvajtay Can you post the compiler errors?

**Comment by tvajtay** [comment]
[buildlog.txt](https://github.com/nclack/whisk/files/732652/buildlog.txt)
One of the additional issues is that Cmake can't find my matlab install so it doesn't add the mex files to the makefile. I can compile Load/Savemeasurements on my own in Matlab using gcc but Load/SaveWhiskers is linked to quite a few files(objects?) that I can't get organized correctly.

Unrelated, but what type of files are the .whiskers .measurements files?

**Comment by nclack** [comment]
I see.

All the link-time dependencies should be in the whiskio_static library.  At compile-time it has to find all the right header files.

whiskers files store information about the shape of traced segments.  The .measurements file store a feature table about the traced segments.

The .whiskers and .measurements files are (custom) binary files.  The whisker_io_v*.c and measurements_io_v*.c files describe the specific binary format.  The formats evolved over the project, so there are different versions (v0,v1,etc..).  I think that version with the highest number is the one that's used.  There's a command line tool that helps convert/inspect the format versions.

**Comment by nclack** [comment]
@tvajtay If you want to try to get the cmake mex build working, the file to look at is:
https://github.com/nclack/whisk/blob/master/3rdParty/FindMatlab-rwp.cmake

**Comment by tvajtay** [comment]
Addendum: Cmake does discover my Matlab install if I run Cmake on windows, I just haven't been able to get Whisk to compile yet on Windows. Cmake documentation says that the FindMatlab package searches for the Matlab install via registry in Windows and Path on Linux. I've added my Matlab root install to path but still no go. Ideally I would want it to run on windows anyway, haven't tried gcc 4.X on windows yet so that is still a possibility.

The reason I'm curious about the .whiskers filetype is that I would like to edit the tracked points in order to remove "noise" from the tracking of facial fur.

**Comment by nclack** [comment]
@tvajtay see https://github.com/nclack/whisk/blob/master/src/whisker_io_whiskbin1.c

**Comment by tvajtay** [comment]
@nclack I wanted to ask you about how to go about getting whisk up to date with c++11. You mentioned that ```inline``` is maybe at fault. Do you think simply removing all uses of inline would be beneficial. I believe that the C++ compiler usually ignores user instances of ```inline``` and allocates memory as it sees fit?

**Comment by nclack** [comment]
@tvajtay Removing all uses of inline should be just fine.

**Comment by tvajtay** [comment]
@nclack sorry, one more question. Was there a specific IDE or project file associated with whisk while you were building it. I see that you have bits of various different languages spread out in the repository and was curious how you organized the build.

**Comment by nclack** [comment]
@tvajtay The readme has a section on building that you can refer to.  You can ignore the python stuff.

**Comment by tvajtay** [comment]
@nclack I was able to successfully build the functions using gcc 5.4 after removing ```inline``` from all respective files. 
[build_log.txt](https://github.com/nclack/whisk/files/814622/build_log.txt)

However when I tried to build the same code with both Visual Studio 2008 and 2015 there were still too many errors and would not build successfully.

Since it builds fine using gcc, I'm instead starting to look at the find_matlab cmake function to see if I can get it to detect matlab on linux somehow, as it has been unsuccessful thus far.

**Comment by cxrodgers** [comment]
Thank @tvajtay and @nclack, I can confirm that removing all instances of the word "inline" from source files fixes my compilation problems (Linux Mint 18). I used these commands to do the replacement:
find . -type f -wholename "./src/*.c" -exec sed -i.bak 's/\<inline\>//g' {} \;
find . -type f -wholename "./include/*.h" -exec sed -i.bak 's/\<inline\>//g' {} \;
find . -type f -wholename "./src/*.p" -exec sed -i.bak 's/\<inline\>//g' {} \;

There’s a couple places where there is a line like “#define inline _inline” that probably shouldn't be edited..

**Comment by nclack** [comment]
@cxrodgers @tvajtay 

I anyone wants to submit a pull request, I'll merge it.  Thanks all.

**Comment by cxrodgers** [comment]
Hi @nclack I've submitted a PR for removing the inline.
