### ISSUE TITLE
splitting a long file: best practices

### ISSUE THREAD

**Issue by gvoysey** [nclack/whisk#38]
I want to start analysis of long whisking bouts (1-2 minutes @ 240fps), and I wanted to pass a few ideas past @nclack  first.

1.   Is splitting up a video into many segments, and then running {trace,measure,classify,reclassify} against each segment, an OK thing to do?  In particular, what are the effects of that decision on preserving whisker identification across segments, if any?  How can I examine n `.whiskers` or `.measurements` files from n runs and extract the same whisker from the series? 

2.  Right now we're shooting 720p video at 240fps.  What, if anything, would be the effects of downsampling this to 360 or 240p  on whisker detection accuracy?  From your paper it looks like this should be safe, but I wanted to make sure. 

Thanks!

**Comment by cxrodgers** [comment]
I have done something very similar to your idea #1 already.
https://github.com/cxrodgers/WhiskiWrap

My understanding is that everything that whisk does is frame-autonomous, that is, every frame is processed in isolation from every other frame. So there should be no change in the results. I wrote my own tools to concatenate the results of each run into a big HDF5 file.

In order to extract the same whisker across the series, you are dependent on whatever classification scheme you use. If you use `classify`, then it is order-based (back to front), and as long as this works correctly in every frame independently, you can extract the same whisker from the entire series.

**Comment by gvoysey** [comment]
@cxrodgers  😱  man i wish I had known about your code beforehand: have a look at https://github.com/MEEI-SPEL/mousetracker  for some serious wheel-reinventing (as well as some non-overlapping work, thankfully).

**Comment by tvajtay** [comment]
I would assume that as long as you ran all the sub videos using the same parameters the whisker ID's should be the same in the measurements file regardless of how many sub videos you analyze. It's interesting that you guys are more focused on the python scripts, while I've just built on the Matlab stuff. Honestly I haven't even looked to see if there is a python `LoadMeasurements`

**Comment by nclack** [comment]
`trace` treats each frame independently and is the only thing that looks at the video files.  So it should be ok to split up videos.

The .whiskers file stores a bunch of curves (whisker segments).  Each of these is indexed (uniquely identified) by a tuple `(frame id, segment id)`.  `frame id` is the number of the frame in the time-series and `segment id` is whatever random integer got assigned during tracing segments within a frame.  This tuple is also used in the .measurements file to cross-reference measurements/annotations to segments from the .whisker file.

So if you wanted to split up a video into a bunch of smaller segments
1. run trace on each smaller video
2. read the .whisker files and update the frame id's for each segment
3. write out the concatenated whisker data

**Comment by nclack** [comment]
As far as down sampling the videos goes: 

I'm not sure what the effect will be on your data.  You'll have to run the controls.

There's a chance you'll have to fiddle with the [parameters file][1] (which gets written out the first time you run).  Especially the `SEED_ON_GRID_LATTICE_SPACING` parameter.

[1]: https://github.com/nclack/whisk/blob/master/src/parameters/default.parameters

**Comment by nclack** [comment]
@tvajtay The python interface should be

**Comment by tvajtay** [comment]
Follow up question since we are on `trace` I'm assuming `batch.py` is faster than trying to run `parfor` with `trace` in Matlab.

Also did you ever encounter issues of lost tracking due to motion blur?

**Comment by nclack** [comment]
(sorry accidentally hit the close button)

The python interface in whisk is pretty complete; I used it for most of the development.  But it's focused mostly on my use and completely unmaintained.

I think parfor/trace should be just as fast as batch.py; nothing fancy there. 

Motion blur is definitely a problem.  That was mostly dealt with on the instrument side by strobing the illumination or reducing exposure times.  I'm not the expert on that side of things though.

**Comment by gvoysey** [comment]
(fwiw i've been using the python bindings because while analysis in matlab is all well and good, it makes me want to pull my teeth out to write relatively real programs in.  That `numpy` and `matplotlib` and `pandas` are giving matlab a run for their money is nearly incidental.. ;-) )

**Comment by tvajtay** [comment]
Yeah I actually just finished analyzing some test videos and cranking down exposure helped immensely.

I actually just call the python scripts/ executables from Matlab since ultimately we do the data analysis and statistics in Matlab, but I guess I'll take another look at the Python interface.

Downsampling wise we reduce our videos from 640 to 320 without significant issues.

**Comment by gvoysey** [comment]
all good news to me, i think!

**Comment by cxrodgers** [comment]
This is probably already clear to anyone who's tried this, but a major challenge with long videos (ours are 500K frames) is that the whiskers files are so large that they cannot be loaded into memory using LoadWhiskers. That's one advantage of chunking: the individual whiskers files are manageable. 

Then, I use HDF5 to stitch together all of the data that is in the individual whiskers files, because then I can just load the individual segments that I need without loading the entire thing.

**Comment by gvoysey** [comment]
I may or may not have 128 gigs of ram at my disposal  😇

**Comment by nclack** [comment]
Does LoadWhiskers die at a 2GB or 4GB limit?  Or are you just running out of RAM?

**Comment by tvajtay** [comment]
Well that's an interesting way to do it. We haven't done anything that big, (maybe 100K frames), and we haven't needed to segment yet.  I've only focused on the `.measurements` files since they are smaller and contain the relevant data I need anyway.

On a side note what video format do you all use for tracing. I've only got Tiff stacks to work consistently.

**Comment by nclack** [comment]
@cxrodgers @tvajtay @gvoysey  I'd like to add links to your related repositories in the README for whisk.  Would that be ok?

This is a bit of an experiment, but I set up a [chat room][2] (using [Discord][1]).  I'll link to that in the README as well.  I'm hoping that might be a better place to exchanging information than this issue tracker :)

[1]: https://discordapp.com/
[2]: https://discord.gg/Y7QJerr

**Comment by tvajtay** [comment]
@nclack Of course, I was trying to think of a way to somehow mesh it with `Whisk` but couldn't think of anything that was really satisfactory.

I'm a big fan of Discord personally.
